import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";
import {
  Geist,
  Geist_Mono,
  Unbounded,
  Zen_Kaku_Gothic_Antique,
  IM_Fell_English_SC,
  Orbitron,
} from "next/font/google";

Unbounded({ subsets: ["latin"] });
Zen_Kaku_Gothic_Antique({
  subsets: ["latin"],
  weight: ["400", "700"],
});
IM_Fell_English_SC({ subsets: ["latin"], weight: "400" });
Orbitron({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "William Rongholt | Portfolio",
  metadataBase: new URL("https://wrongholt.com"),
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
